USE [Binance]
GO

/****** Object:  StoredProcedure [dbo].[BuyCrypto]    Script Date: 11/28/2021 3:43:31 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[BuyCrypto]
	-- Add the parameters for the stored procedure here
	@SYMBOLS VARCHAR(500)
AS
BEGIN

	DECLARE @URL NVARCHAR(MAX) = 'HTTP://LOCALHOST:5001/API/V1/BINANCE/BUY';
	DECLARE @OBJECT AS INT;
	DECLARE @RESPONSETEXT AS VARCHAR(8000);
	DECLARE @CODE AS INT;

	DECLARE @SYMBOL VARCHAR(100);
	DECLARE @TEMPLATE AS VARCHAR(1000) = 
	'{
		"symbol": "@SYMBOL",
		"amount": 11
	},';
	DECLARE @REQ AS VARCHAR(2000) = '';

	DECLARE @SYMBOL_RESPONSE AS VARCHAR(2000);
	DECLARE @SYMBOL_ERROR AS VARCHAR(200);
	DECLARE @RESPONSE_SYMBOL AS VARCHAR(100);
	DECLARE @RESPONSE_AMOUNT AS DECIMAL(20,8);

	IF @SYMBOLS IS NULL
		BEGIN
			RETURN;
		END

	DECLARE SYMBOLS_CURSOR CURSOR FOR 
	SELECT VALUE FROM STRING_SPLIT(@SYMBOLS, ','); 

	OPEN SYMBOLS_CURSOR
	FETCH NEXT FROM SYMBOLS_CURSOR INTO @SYMBOL

		WHILE @@FETCH_STATUS = 0  
		BEGIN

			SET @REQ += REPLACE(@TEMPLATE, '@SYMBOL', @SYMBOL);
	
		FETCH NEXT FROM SYMBOLS_CURSOR INTO @SYMBOL
		END 
	
	CLOSE SYMBOLS_CURSOR;  
	DEALLOCATE SYMBOLS_CURSOR;

	SET @REQ = SUBSTRING(@REQ, 1, LEN(@REQ)-1)
	SET @REQ = '[' + @REQ + ']';

	EXEC SP_OACREATE 'MSXML2.XMLHTTP', @OBJECT OUT;
	EXEC SP_OAMETHOD @OBJECT, 'OPEN', NULL, 'POST',
       @URL,
       'FALSE'
	EXEC sp_OAMethod @Object, 'setRequestHeader', null, 'Content-Type', 'application/json'
	EXEC sp_OAMethod @Object, 'send', null, @REQ
	EXEC @CODE = SP_OAMETHOD @OBJECT, 'SEND'
	EXEC SP_OAMETHOD @OBJECT, 'RESPONSETEXT', @RESPONSETEXT OUTPUT
	EXEC SP_OAGETPROPERTY @OBJECT, 'STATUS', @CODE OUT
	EXEC SP_OADESTROY @OBJECT
	
	IF @CODE = 200
	BEGIN
		DECLARE RESPONSE_CURSOR CURSOR FOR 
		SELECT VALUE FROM OPENJSON(@RESPONSETEXT);

		OPEN RESPONSE_CURSOR
		FETCH NEXT FROM RESPONSE_CURSOR INTO @SYMBOL_RESPONSE

		WHILE @@FETCH_STATUS = 0  
		BEGIN

			SELECT @RESPONSE_SYMBOL = 
			VALUE 
			FROM OPENJSON(@SYMBOL_RESPONSE) A
			WHERE [KEY] = 'symbol';

			SELECT @RESPONSE_AMOUNT = 
			VALUE 
			FROM OPENJSON(@SYMBOL_RESPONSE) A
			WHERE [KEY] = 'amount';

			SELECT @SYMBOL_ERROR = 
			VALUE 
			FROM OPENJSON(@SYMBOL_RESPONSE) A
			WHERE [KEY] = 'errorResponse';

			IF @SYMBOL_ERROR IS NOT NULL
			BEGIN
				INSERT INTO ODERERROR(Symbol, ErrorMessage, OrderType, CreatedAt)
				SELECT  @RESPONSE_SYMBOL, @SYMBOL_ERROR, 'BUY', GETDATE();

				DELETE FROM [Transaction]
				WHERE Symbol = @SYMBOL_RESPONSE;
			END
			ELSE
			BEGIN
				UPDATE [Transaction]
				SET MoneyIn = @RESPONSE_AMOUNT
				WHERE Symbol = @RESPONSE_SYMBOL;
			END
	
		FETCH NEXT FROM RESPONSE_CURSOR INTO @SYMBOL_RESPONSE
		END 
	
		CLOSE RESPONSE_CURSOR;  
		DEALLOCATE RESPONSE_CURSOR;

	END
	ELSE 
	BEGIN
		INSERT INTO ODERERROR(Symbol, ErrorMessage, OrderType, CreatedAt)
		SELECT SUBSTRING(@SYMBOLS, 1,99), SUBSTRING(@RESPONSETEXT, 1, 299), 'BUY', GETDATE();
	END

END
GO


